import Head from "next/head";
import Header from "../component/Header";
import Navbar from "../component/Navbar";
import Result from "../component/Result";
import request from "../utils/request";

export default function Home({results}) {
  console.log(results)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header></Header>
      {/* Navbar */}
      <Navbar></Navbar>
      {/* Result */}
      <Result results={results}></Result>
    </div>
  );
}
export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";
  const requests = await fetch(`https://api.themoviedb.org/3${request[genre].url}`);
  const data = await requests.json();

  return {
    props: {
      results: data.results,
    },
  };
}
